# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3B_rri-fqv2yUTk2u3YAY9BWr0LPoCY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load the dataset
iris = pd.read_csv("Iris.csv")

# Remove the unneeded column
iris.drop('Id', axis=1, inplace=True)

# Split the dataset into features and target variable
X = iris.drop('Species', axis=1)
y = iris['Species']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Build the SVM classifier
svm_model = SVC()

# Train the SVM classifier
svm_model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = svm_model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

#Function to show the final data
def show_final_data(X, y, predictions):
    final_data = pd.DataFrame({
        'SepalLengthCm': X['SepalLengthCm'],
        'SepalWidthCm': X['SepalWidthCm'],
        'PetalLengthCm': X['PetalLengthCm'],
        'PetalWidthCm': X['PetalWidthCm'],
        'Species': y,
        'Predicted_Species': predictions
    })
    print("Final Data:")
    print(final_data)

# Show the final data
show_final_data(X_test, y_test, y_pred)